### ISSUE TITLE
Script API documentation is missing

### ISSUE THREAD

**Issue by phette23** [openequella/openequella.github.io#1]
First off, thanks so much for putting this in a public place, it'll be very helpful.

One piece of EQUELLA documentation I constantly consult is the "Script API" documentation which describes all the custom functions available in Freemarker templates, on-load & on-submit scripts inside contrib wizards, manage resources scripts, etc. Will this be added? It is referenced in the [Advanced Scripting Guide](https://github.com/equella/equella.github.io/blob/master/guides/AdvancedScriptingGuide.md) ("For a full description of all the available objects and their methods please refer to the Script API documentation.") but not present in this repo as far as I can tell.

**Comment by cbeach47** [comment]
Hi @phette23 - the scripting API docs will be added to this docs repo shortly.  Tracked in https://github.com/equella/Equella/issues/104

**Comment by cbeach47** [comment]
@phette23 - the API docs are now available:  https://equella.github.io/ , and scroll down to 'API', and 'API Guides / Tutorials'.  You'll need to view in the pretty print view of the repo, otherwise the html of the API docs won't be rendered.

**Comment by phette23** [comment]
Awesome! Thanks!
