### ISSUE TITLE
reset the equella system password

### ISSUE THREAD

**Issue by rkhyd** [openequella/openequella.github.io#13]
The is no documentation regarding how to reset the system password of equella. please let me know the procedure to reset it. thanks

**Comment by rkhyd** [comment]
i did find the documentation here.. http://equella.github.io/guides/AdditionalGeneralInfoHelp.html#reset-the-server-admin-pages-password
but even after resetting the password, it still says invalid credentials..
not sure why!!!!

**Comment by edalex-ian** [comment]
Hi @rkhyd ,

I note you've found the doco now, and so at least there's no issue for the documentation (and so I'll close this issue). However if you're still having issues with the resenting of passwords, feel free to post on the users mailing list at https://groups.google.com/a/apereo.org/forum/#!forum/equella-users or raise an issue over in equella/Equella if you think there is a bug.

Thanks.
