### ISSUE TITLE
Text stemming not working in other languages, i.e. German

### ISSUE THREAD

**Issue by NextEdServices** [openequella/openequella.github.io#44]
When searching content with German words, the stemming shows incorrect results:
i.e. the search for "Baum" and "Bäume" (Plural of "Baum") shows up inequal results.
It should show up same result list. (The content is 100% German text)

The stemming for the English language is working: 
search result list i.e. of cook-cooked-cooking is identical.

This issue may also be relevant for other supported languages.

**Comment by edalex-ian** [comment]
This ticket should've been against openEQUELLA itself. But regardless, it was as a result addressed over there by openequella/openEQUELLA#1009

Closing as done.
