### ISSUE TITLE
Error when importing institution tgz file

### ISSUE THREAD

**Issue by thanhnv3690** [openequella/openequella.github.io#53]
I installed the lastest version of openEquella and tried to upload institution but the system showed "Please import a institution file". I checked in tomcat log and it has this error
"<tr><td>22:09:16,312</td><td></td><td><font color="#993300"><strong>ERROR</strong></font></td><td>TomcatLog</td>
<td>Servlet.service() for servlet [default] in context with path [/] threw exception</td></tr>
<tr><td bgcolor="#993300" style="color:White; font-size : xx-small;" colspan="5">java.lang.StringIndexOutOfBoundsException: String index out of range: -1
<br>&nbsp;&nbsp;&nbsp;&nbsp;	at java.lang.String.substring(String.java:1931)
<br>&nbsp;&nbsp;&nbsp;&nbsp;	at com.tle.web.institution.InstitutionFilter.doNormal(InstitutionFilter.java:225)
<br>&nbsp;&nbsp;&nbsp;&nbsp;	at com.tle.web.institution.InstitutionFilter.doFilterInternal(InstitutionFilter.java:174)
<br>&nbsp;&nbsp;&nbsp;&nbsp;	at com.tle.web.core.filter.OncePerRequestFilter.filterRequest(OncePerRequestFilter.java:40)
<br>&nbsp;&nbsp;&nbsp;&nbsp;	at com.tle.web.dispatcher.RequestDispatchFilter.doFilter(RequestDispatchFilter.java:66)
<br>&nbsp;&nbsp;&nbsp;&nbsp;	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
<br>&nbsp;&nbsp;&nbsp;&nbsp;	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
<br>&nbsp;&nbsp;&nbsp;&nbsp;	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
<br>&nbsp;&nbsp;&nbsp;&nbsp;	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
<br>&nbsp;&nbsp;&nbsp;&nbsp;	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:528)
<br>&nbsp;&nbsp;&nbsp;&nbsp;	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
<br>&nbsp;&nbsp;&nbsp;&nbsp;	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
<br>&nbsp;&nbsp;&nbsp;&nbsp;	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
<br>&nbsp;&nbsp;&nbsp;&nbsp;	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
<br>&nbsp;&nbsp;&nbsp;&nbsp;	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
<br>&nbsp;&nbsp;&nbsp;&nbsp;	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
<br>&nbsp;&nbsp;&nbsp;&nbsp;	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:810)
<br>&nbsp;&nbsp;&nbsp;&nbsp;	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
<br>&nbsp;&nbsp;&nbsp;&nbsp;	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
<br>&nbsp;&nbsp;&nbsp;&nbsp;	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
<br>&nbsp;&nbsp;&nbsp;&nbsp;	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
<br>&nbsp;&nbsp;&nbsp;&nbsp;	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
<br>&nbsp;&nbsp;&nbsp;&nbsp;	at java.lang.Thread.run(Thread.java:748)"

Please help me

**Comment by phette23** [comment]
This is the repo for openEQUELLA documentation, I think you probably want to report this at the repo for the main application https://github.com/openequella/openequella

**Comment by thanhnv3690** [comment]
Thank you. It's my mistake
