### ISSUE TITLE
When run opnequella on https cant open admin-console-package doesnot connect to the institution

### ISSUE THREAD

**Issue by miraboureslan** [openequella/openequella.github.io#82]
we are running openequella with proxy for SSL 
we can access the institution without any errors but cant access the administration console
port used:8443 
when connect to the admin console we reach the popup to enter username and password 
after that the jars the should be located in the cache folder are not getting downloaded 
to the launcher doesnot display anything and we can see in the task manager that it is still running

**Comment by edalex-ian** [comment]
Hi there @miraboureslan 

Thank you for your query. I've moved the issue over to the appropriate project and will follow up with you there.

openequella/openEQUELLA-admin-console-package#41

Thanks,
Ian.
