### ISSUE TITLE
Where to get latest QA release fore V6.4

### ISSUE THREAD

**Issue by exing1984** [openequella/openequella.github.io#9]
Hi there, 
From the V6.5 upgrade guide that mentioned below:
Upgrade EQUELLA to version 6.5
EQUELLA 6.5 uses in-place upgrades, ensuring your institution’s decision to upgrade EQUELLA is
faster, easier and cheaper.
NOTE: For EQUELLA versions prior to 6.4, an upgrade to 6.4 QA4 must be run first, then the upgrade
to 6.5.

Our institution's Equella currently running on 6.4-QA1 version, I don't where to get latest QA release package to download, Is anyone got that package to share?

Many thanks.

**Comment by edalex-ian** [comment]
Hi @exing1984 ,

Do you still require assistance with this? If not, I'll close, otherwise I'll chase up for you.

Cheers.

**Comment by edalex-ian** [comment]
Nothing heard, closing.
